apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
  labels:
    tier: control-plane
    component: kube-controller-manager
spec:
  hostNetwork: true
  priorityClassName: system-node-critical
  containers:
  - name: kube-controller-manager
    image: registry.k8s.io/kube-controller-manager:v1.30.3
    command:
    - kube-controller-manager
    - --kubeconfig=/var/lib/kubelet/kubeconfig
    - --service-cluster-ip-range=10.10.0.0/24
    - --cluster-cidr=192.168.0.0/24
    - --leader-elect=false
    - --cloud-provider=external
    - --cluster-name=kubernetes
    - --root-ca-file=/var/lib/kubelet/ca.crt
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca.key
    - --use-service-account-credentials=true
    - --controllers=*,csrsigning
    - --v=0
    volumeMounts:
    - name: kubelet
      mountPath: /var/lib/kubelet
      readOnly: true
    - name: pki
      mountPath: /etc/kubernetes/pki
      readOnly: true
  volumes:
  - name: kubelet
    hostPath:
      path: /var/lib/kubelet
      type: Directory
  - name: pki
    hostPath:
      path: /etc/kubernetes/pki
      type: Directory

